print("Ahoj Malináři Vlaďo, Slávjenko a Paťke")
print("Ahoj Malináři Vlaďo, Slávjenko a Paťke")
print("Ahoj Malináři Vlaďo, Slávjenko a Paťke")
print("Ahoj Malináři Vlaďo, Slávjenko a Paťke")
print("Ahoj Malináři Vlaďo, Slávjenko a Paťke")
